### ISSUE TITLE
Generate command from tutorial does not work on Debian 10 Buster with Nix

### ISSUE THREAD

**Issue by MarekDudek** [srid/ema-docs#18]
Hello

`nix run . -- -C ./content gen $(pwd)/output` command results in 

> warning: Git tree '/path/to/repo' is dirty
> 
> Invalid option `-C'
> Usage: ema-template [COMMAND | COMMAND]
> Ema - static site generator

Debian 10 Buster, Xix multiuser installation with Flakes enabled.

**Comment by srid** [comment]
@MarekDudek Try `cd content && nix run .. -- gen /tmp/`

`-C` was removed in newer Ema.

**Comment by srid** [comment]
Where did you see this command being used, btw?

**Comment by MarekDudek** [comment]
@srid 

Thanks for the workaround.
I took command from (https://ema.srid.ca/start/tutorial), still there.
